title: Bitcoin Research Day
description: > # this means to ignore newlines until "baseurl:"
  Second edition of the Bitcoin Research Day
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brd.chaincode.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

logo: "css/img/logo-small-transparent.png"

include: ['_pages']

plugins:
  - jekyll-sitemap

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ChaincodeLabs

# Build settings
markdown: kramdown
permalink: pretty
